apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-system
  namespace: argo-cd
spec:
  sourceRepos:
  - 'https://github.com/zsolt-keseru-epam/meetup-argo-stack'
  destinations:
  - namespace: 'argo-cd'
    server: 'https://kubernetes.default.svc'
  - namespace: 'argo-events'
    server: 'https://kubernetes.default.svc'
  - namespace: 'argo-workflows'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'