apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - 'https://github.com/zsolt-keseru-epam/meetup-argo-stack'
  destinations:
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  - namespace: 'argo-events'
    server: 'https://kubernetes.default.svc'
  - namespace: 'argo'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'