apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: argo-system
  source:
    path: kustomize/sealed-secrets
    repoURL: https://github.com/zsolt-keseru-epam/meetup-argo-stack
    targetRevision: HEAD
  syncPolicy: {}
