apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-system
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: meta
  source:
    path: kustomize/argo-cd-meta-projects/argo-system
    repoURL: https://github.com/zsolt-keseru-epam/meetup-argo-stack
    targetRevision: main
  syncPolicy: {}
