apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
  namespace: argo-cd
spec:
  sourceRepos:
  - 'https://github.com/zsolt-keseru-epam/meetup-argo-stack'
  destinations:
  - namespace: 'argo-cd'
    server: 'https://kubernetes.default.svc'

  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: AppProject
  - group: 'argoproj.io'
    kind: Application
  
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'