apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: meta
  source:
    path: kustomize/argo-cd-meta-project/pipeline
    repoURL: https://github.com/zsolt-keseru-epam/meetup-argo-stack
    targetRevision: main
  syncPolicy: {}
