apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-cd
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  rules:
    - host: argo-cd.74.220.20.216.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: 80