apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd
spec:
  rules:
    - host: argo-cd.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-server
                port:
                  number: 80