resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.1.6
- ingress.yaml

namespace: argo-cd

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cmd-params-cm
    data:
      server.insecure: "true"

# patchesJson6902:
# - patch: |-
#     - { "op": "add", "path": "/data", "value": { "server.insecure": "true" }}
#   target:
#     kind: ConfigMap
#     name: "argocd-cmd-params-cm"
