apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    argo-combined-app:
      owner: zsolt-keseru-epam
      repository: argo-combined-app
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://myapp-webhook.74.220.20.216.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json