apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-pipelines
    server: https://kubernetes.default.svc
  project: pipeline
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/zsolt-keseru-epam/argo-combined-app
    targetRevision: master
  syncPolicy: {}
